test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,23 @@
 #!/bin/bash
 
-echo "-----> adding /app/.apt/lib/x86_64-linux-gnu to LD_LIBRARY_PATH for tesseract"
-export LD_LIBRARY_PATH="/app/.apt/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
+ENV_DIR=$3
+TESSERACT_VERSION=$(cat $ENV_DIR/TESSERACT_VERSION)
+
+export TESSDATA_PREFIX=$(cat $ENV_DIR/TESSDATA_PREFIX)
+
+echo "-----> adding .apt/lib/x86_64-linux-gnu to LD_LIBRARY_PATH for tesseract"
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
+cat <<EOF >$BUILD_DIR/.profile.d/tesseract.sh
+export LD_LIBRARY_PATH="\$HOME/.apt/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH"
+EOF
+
+echo "       checking tesseract version"
+TESSERACT_VERSION_OUTPUT="$(tesseract -v)"
+if $TESSERACT_VERSION_OUTPUT | grep -q $TESSERACT_VERSION
+then
+  echo "       version $TESSERACT_VERSION found"
+else
+  echo "       version $TESSERACT_VERSION not found"
+  echo "       $TESSERACT_VERSION_OUTPUT"
+  exit 1
+fi
