test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,30 +1,16 @@
 #!/bin/bash
 
-BUILD_DIR=$1
 TESSERACT_VERSION=4.1.1
-ARCHIVE_REMOTE=https://notarize-dev-static-assets.s3.amazonaws.com/lib/tesseract-$TESSERACT_VERSION.tar.gz
-REPO_DIR=$BUILD_DIR/tesseract
-APT_CACHE_DIR=$BUILD_DIR/apt/cache
-APT_STATE_DIR=$BUILD_DIR/apt/state
-APT_SOURCES_DIR=$BUILD_DIR/apt/sources
-APT_SOURCES=$APT_SOURCES_DIR/sources.list
 
-echo "-----> creating local tesseract $TESSERACT_VERSION repo in $REPO_DIR from $ARCHIVE_REMOTE"
+echo "-----> fixing LD_LIBRARY_PATH"
+export LD_LIBRARY_PATH="/app/.apt/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
 
-mkdir -p $REPO_DIR
-curl -s $ARCHIVE_REMOTE | tar xz -C $BUILD_DIR
-
-echo "       adding local tesseract $TESSERACT_VERSION repo to source list"
-
-mkdir -p $APT_CACHE_DIR/archives/partial
-mkdir -p $APT_STATE_DIR/lists/partial
-mkdir -p $APT_SOURCES_DIR
-cat "/etc/apt/sources.list" > $APT_SOURCES
-echo "deb [trusted=yes] file:$REPO_DIR ./" >> $APT_SOURCES
-
-APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR -o dir::etc::sourcelist=$APT_SOURCES -o dir::etc::sourceparts=/dev/null"
-apt-get update $APT_OPTIONS
-
-echo "       installing tesseract $TESSERACT_VERSION from local repo"
-
-apt-get install -y $APT_OPTIONS tesseract-ocr
+echo "       checking tesseract version"
+if ./somecommand | grep -q $TESSERACT_VERSION
+then
+  echo "       version $TESSERACT_VERSION found"
+else
+  echo "       version $TESSERACT_VERSION not found"
+  echo tesseract -v
+  exit 1
+fi
